[package]
name = "comedy-writer-rs"
version = "0.1.0"
authors = ["InternationalDefy <DTEye1533014901@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oorandom = "11.1.2"